name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test

  deploy:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: zarif98sjs/C-Compiler-Code-Generation-CI-CD@main
          with:
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: 'midnight.scream98@gmail.com'
            use_git: true
